version: "3"

services:
  go-svc-template-app:
      command: reflex -sr '\.go$|\.mod$' -- sh -c "go run cmd/main.go"
      build:
        dockerfile: Dockerfile.local
        context: .
      depends_on:
        - go-svc-template-db
        - go-svc-template-redis
      environment:
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=go-svc-db
        - DB_HOST=go-svc-template-db
        - DB_PORT=5432
        - HTTP_SERVER_PORT=3003
        - CACHE_HOST=go-svc-template-redis
        - CACHE_PORT=6380
        - SERVICE_NAME=go-svc-template
        - ENVRIONMENT=local
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      ports:
        - "3003:3003"
  go-svc-template-redis:
    image: redis:latest
    ports:
      - "6380:6380"
  go-svc-template-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'go-svc-db'
    ports:
      - "5432:5432"